/**
 * Playwright global setup for managed E2E mode.
 *
 * When E2E_MANAGED=true:
 *   1. Starts a WireMock container (stubs Ollama API)
 *   2. Starts the Spring Boot backend pointing at WireMock
 *   3. Waits for the app to be healthy before tests begin
 *
 * When E2E_MANAGED is not set: no-op (assumes app already running).
 */

import { GenericContainer, Wait } from 'testcontainers';
import { spawn, execSync } from 'child_process';
import { existsSync, mkdirSync, writeFileSync, rmSync } from 'fs';
import { homedir, tmpdir } from 'os';
import { join } from 'path';

const BACKEND_PORT = process.env.BACKEND_PORT || '8082';
const BASE_URL = `http://localhost:${BACKEND_PORT}`;
const DB_PATH = join(tmpdir(), `briefen-e2e-${Date.now()}.db`);

// ── Java detection ────────────────────────────────────────────────────────────

function findJavaHome() {
  const sdkman = join(homedir(), '.sdkman', 'candidates', 'java', 'current');
  if (existsSync(join(sdkman, 'bin', 'java'))) return sdkman;

  try {
    return execSync('/usr/libexec/java_home', { encoding: 'utf8', stdio: 'pipe' }).trim();
  } catch { /* not macOS or not configured */ }

  if (process.env.JAVA_HOME && existsSync(join(process.env.JAVA_HOME, 'bin', 'java'))) {
    return process.env.JAVA_HOME;
  }

  throw new Error('Java not found. Install via sdkman or set JAVA_HOME.');
}

// ── Health-check polling ──────────────────────────────────────────────────────

async function waitForHealth(url, { timeout = 120_000, interval = 1500 } = {}) {
  const deadline = Date.now() + timeout;
  let lastError;
  while (Date.now() < deadline) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(3000) });
      if (res.status === 200) {
        const body = await res.json();
        if (body.status === 'UP') return;
      }
    } catch (e) {
      lastError = e;
    }
    await new Promise(r => setTimeout(r, interval));
  }
  throw new Error(`Health check timed out at ${url}: ${lastError?.message ?? 'unknown'}`);
}

// ── WireMock stub helpers ─────────────────────────────────────────────────────

async function addStub(adminUrl, stub) {
  const res = await fetch(`${adminUrl}/__admin/mappings`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(stub),
  });
  if (!res.ok) throw new Error(`WireMock stub registration failed: ${res.status}`);
}

async function configureOllamaStubs(adminUrl) {
  // OllamaHealthIndicator calls GET /api/tags
  await addStub(adminUrl, {
    request: { method: 'GET', urlPath: '/api/tags' },
    response: {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
      jsonBody: { models: [{ name: 'gemma3:4b' }] },
    },
  });

  // OllamaSummarizerService calls POST /api/generate
  await addStub(adminUrl, {
    request: { method: 'POST', urlPath: '/api/generate' },
    response: {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
      jsonBody: {
        model: 'gemma3:4b',
        response: [
          '# Managed E2E Test Article',
          '',
          'This summary was generated by WireMock during managed E2E testing.',
          '',
          'The article discusses important topics in software testing, including',
          'integration strategies and end-to-end validation of real system behaviour.',
          '',
          '## Key Quotes',
          '',
          '> "End-to-end tests provide confidence that the full system works together"',
          '',
          '> "WireMock enables reliable, fast API stubbing without real dependencies"',
        ].join('\n'),
        done: true,
        done_reason: 'stop',
        total_duration: 1000000000,
      },
    },
  });
}

// ── Backend process management ────────────────────────────────────────────────

function startBackend(javaHome, ollamaBaseUrl) {
  const backendDir = join(process.cwd(), 'backend');
  mkdirSync(backendDir, { recursive: true });

  const env = {
    ...process.env,
    JAVA_HOME: javaHome,
    PATH: `${join(javaHome, 'bin')}:${process.env.PATH}`,
    OLLAMA_BASE_URL: ollamaBaseUrl,
    BRIEFEN_DB_PATH: DB_PATH,
    SERVER_PORT: BACKEND_PORT,
  };

  const proc = spawn('./mvnw', ['spring-boot:run', '-q'], {
    cwd: backendDir,
    env,
    stdio: ['ignore', 'pipe', 'pipe'],
    detached: false,
  });

  // Surface fatal errors to the console without flooding output
  proc.stderr.on('data', d => {
    const text = d.toString();
    if (/ERROR|Exception|BUILD FAILURE/i.test(text)) process.stderr.write(text);
  });

  proc.on('error', err => { throw err; });

  return proc;
}

// ── Global setup entry point ──────────────────────────────────────────────────

export default async function globalSetup() {
  if (process.env.E2E_MANAGED !== 'true') {
    console.log('[e2e] E2E_MANAGED not set — assuming app is running at', process.env.BASE_URL || 'http://localhost:8080');
    return;
  }

  console.log('[e2e] Starting managed E2E environment…');

  // 1. Start WireMock
  console.log('[e2e] Starting WireMock container…');
  const wiremock = await new GenericContainer('wiremock/wiremock:3.10.0')
    .withExposedPorts(8080)
    .withWaitStrategy(Wait.forListeningPorts())
    .start();

  const wiremockPort = wiremock.getMappedPort(8080);
  const wiremockUrl = `http://localhost:${wiremockPort}`;
  console.log(`[e2e] WireMock running at ${wiremockUrl}`);

  // 2. Configure stubs
  await configureOllamaStubs(wiremockUrl);
  console.log('[e2e] Ollama stubs configured');

  // 3. Find Java and start Spring Boot
  const javaHome = findJavaHome();
  console.log(`[e2e] Java at: ${javaHome}`);
  console.log('[e2e] Starting Spring Boot (this may take ~60 s on first run)…');

  const backendProc = startBackend(javaHome, wiremockUrl);

  // 4. Wait for Spring Boot health
  console.log(`[e2e] Waiting for health at ${BASE_URL}/actuator/health…`);
  await waitForHealth(`${BASE_URL}/actuator/health`);
  console.log('[e2e] Backend healthy — tests starting');

  // 5. Persist state for globalTeardown (same Node.js process)
  global.__E2E_WIREMOCK__ = wiremock;
  global.__E2E_BACKEND__ = backendProc;
  global.__E2E_DB_PATH__ = DB_PATH;

  // 6. Expose the base URL for test files via env
  process.env.BASE_URL = BASE_URL;
}
